/**
 * The site's own addresses, in one place.
 *
 * These strings are hardcoded to the apex rather than derived from the incoming
 * request, and that is the entire point of the file. The waitlist is served
 * byte-identically on employsi.com.au and on the workers.dev URL; anything that
 * names an address — the canonical link, og:url, og:image, the sitemap — has to
 * name the SAME address from every copy, or each copy declares itself the
 * original and the ranking splits across them.
 *
 * Constants only. This is imported by src/server.ts, which runs on every
 * request including the cold one, so nothing here may pull in a dependency.
 */

/** The one hostname the product is advertised at. */
export const MARKETING_APEX = "employsi.com.au";

/** An alias for the apex, 301'd to it in src/server.ts. */
export const MARKETING_WWW = "www.employsi.com.au";

/** Origin form, no trailing slash — for joining paths onto. */
export const SITE_ORIGIN = `https://${MARKETING_APEX}`;

/**
 * The landing page's canonical address, WITH the trailing slash.
 *
 * The slash is not decorative: `https://employsi.com.au` and
 * `https://employsi.com.au/` are the same page but not the same string, and a
 * canonical tag that disagrees with the sitemap's `<loc>` about which spelling
 * is correct gives a crawler two candidates for one document. Everything here
 * uses the slashed form.
 */
export const CANONICAL_URL = `${SITE_ORIGIN}/`;

/**
 * The 1200x630 social card, regenerated by scripts/gen-og-image.sh.
 *
 * ABSOLUTE, because og:image is the one image URL in the document that is not
 * resolved against the page. Facebook, LinkedIn and Slack fetch it out of band
 * with no base URL to hand, and a relative path is simply dropped — which
 * reads, in a feed, as a link with no picture at all.
 */
export const OG_IMAGE_URL = `${SITE_ORIGIN}/og-image.png`;
export const OG_IMAGE_WIDTH = "1200";
export const OG_IMAGE_HEIGHT = "630";
