import { useEffect, useMemo, useRef, useState } from "react";
import { useQuery } from "@tanstack/react-query";
import type { TickerItem } from "../data/companies";
import { getLiveSkillTrends, TREND_WINDOWS } from "../lib/jobHistoryFn";
import type { TrendWindow } from "../lib/jobHistoryFn";
import { fmtPay, FX_AS_AT } from "../lib/salaryParse";
import { useAppStore } from "../state/store";

/**
 * The skills trend ticker, built from `Skills Trend Ticker.dc.html` in the
 * Employsi Design System project.
 *
 * The first pass at this restyled the existing strip to approximate the design.
 * This one is a port of the design's own markup, element for element: the dark
 * status chip with its window label, the masked marquee, the row as
 * name → sparkline → delta chip with a rotating stroked arrow, and the control
 * cluster (window cycle + pause) behind a hairline divider on the right.
 *
 * Two deliberate departures, both because the design's mock had no real data
 * behind it:
 *
 *  1. The design cycles 24h/7d/30d by multiplying one delta by 1 / 2.1 / 3.4.
 *     Here each window is measured independently against its own prior window
 *     (see TREND_WINDOWS in jobHistoryFn), so switching re-reads the archive
 *     rather than rescaling a single figure. When the archive has nothing for
 *     ANY window the ticker falls back to the static seed and the window button
 *     is disabled, because there is no second window to switch to.
 *  2. The design's mock churns values every 2s and flashes the chip to mark the
 *     change. Our figures are measured, and the previous implementation drifted
 *     them by up to ±1.2pp to imitate that liveness — which meant the number on
 *     screen was not the number measured. The drift is gone. The flash is kept
 *     and fires when a value genuinely changes: a fresh archive read, or a
 *     window switch.
 *
 *  3. The design's row carries a pay figure ("$172k") from a hand-written table
 *     of sixteen skills. Ours is measured: the median annual salary advertised
 *     across the live vacancies demanding that skill, market-wide and
 *     normalised to AUD. Three consequences the design did not have to think
 *     about, all handled in lib/salaryParse:
 *
 *       • CURRENCY, PERIOD and MAGNITUDE all have to be recovered before two
 *         ads can be compared, and none is reliably in the string. Adzuna
 *         writes a bare "72,038" for San Jose and "21,280–22,800" for London;
 *         Singapore and Manila advertise monthly; Zhaopin advertises in 万.
 *       • Rates are PINNED, not fetched live (data/fxRates.ts, regenerated by
 *         scripts/gen-fx-rates.py), so the figure moves when hiring moves and
 *         not when the dollar does. The capture date is in the tooltip.
 *       • A skill whose live ads mostly do not state a salary shows NO figure,
 *         rather than a thin median or a dash — the same rule the sparkline
 *         follows. 73 of the taxonomy's skills currently clear the floor.
 *
 *     The figure is also the same in all three windows on purpose: it is a
 *     level ("what these roles pay now") where the percentage is a movement
 *     over the selected window. That distinction is why the delta chip carries
 *     a small "DEMAND" label — a percentage sitting beside a dollar amount
 *     otherwise reads as a change in the pay.
 *
 * The pause button therefore stops the marquee rather than a value churn that
 * no longer exists, and its tooltip says so ("Pause ticker", not the design's
 * "Pause updates").
 *
 * WHY THERE IS NO LONGER A SEED
 * While the archive read was in flight this showed TICKER_BASE, a hand-written
 * list that existed so the pill would not be empty for a moment. Two things were
 * wrong with it, and they compounded:
 *
 *   • Six of its sixteen rows were COMPANIES — Fortescue, BHP, Woodside, Rio
 *     Tinto, Santos, South32 — tagged "Headcount". This strip says "Skills in
 *     demand". A company is not a skill, and no live path can produce one: the
 *     server drops any name not in SKILL_CATEGORY. They could only ever have
 *     come from here.
 *   • Every percentage in it was invented. "Fortescue +12.3%" is not a
 *     measurement of anything, and it sat in a ticker whose whole claim is that
 *     it is live.
 *
 * So the loading state is now a skeleton: name-shaped placeholders and no
 * numbers. It says "reading" without asserting anything, which is what the
 * empty and no-history states already do.
 */

// Sparkline geometry, matching the design's spark(): a 48x18 box with the line
// inset to x 1..47, y 2..16 so the 1.6px stroke stays inside it.
const SPARK_W = 48;
const SPARK_H = 18;

/**
 * Daily live-vacancy counts → an SVG path, scaled to the box.
 *
 * Returns null when there is nothing honest to draw: no series (the static seed
 * has none), fewer than two points, or a flat line. The row then renders without
 * a sparkline rather than with a fabricated one — the shape is the whole point,
 * so a placeholder would be actively misleading.
 */
function sparkPath(series: number[] | undefined): string | null {
  if (!series || series.length < 2) return null;
  const lo = Math.min(...series);
  const hi = Math.max(...series);
  if (hi === lo) return null;
  return series
    .map((v, i) => {
      const x = 1 + (i / (series.length - 1)) * 46;
      // SVG y grows downward, so a higher count sits nearer the top.
      const y = 16 - ((v - lo) / (hi - lo)) * 14;
      return `${i ? "L" : "M"}${x.toFixed(1)} ${y.toFixed(1)}`;
    })
    .join(" ");
}

// The design's three states: rising, falling, and flat — flat is grey with the
// arrow turned on its side, and exists so a ~0% row doesn't read as a rise.
type Dir = "up" | "down" | "flat";
const dirOf = (v: number): Dir => (v >= 0.15 ? "up" : v <= -0.15 ? "down" : "flat");

// Stable reference, so the empty state does not churn `items` identity.
const EMPTY_ITEMS: TickerItem[] = [];
// Enough placeholder rows to fill the pill at any width.
const SKELETON = [72, 108, 88, 124, 96, 80, 116, 92];

export function Ticker({ hidden }: { hidden: boolean }) {
  // Real, market-wide skill-demand movers from the D1 job archive, for all three
  // windows at once (one scan serves them all). Refreshes once a day — the
  // archive only changes on the daily cron — and falls back to the static seed
  // while loading or before the archive has enough history.
  const {
    data: live,
    isPending: pending,
    isError: failed,
  } = useQuery({
    queryKey: ["liveSkillTrends"],
    queryFn: () => getLiveSkillTrends(),
    staleTime: 6 * 60 * 60 * 1000,
    gcTime: 24 * 60 * 60 * 1000,
    // RETRY, and recover on refocus.
    //
    // This was `retry: false`, and that is the likeliest reason the ticker
    // showed figures on one load and nothing on the next. The read behind it
    // is not cheap — it reconstructs daily series across the whole archive —
    // so an occasional failure or timeout is expected. Without a retry a
    // single one left `data` undefined for the WHOLE session: nothing refetches
    // it, staleTime is six hours, and the bar sat on its loading shimmer with
    // no way back short of a reload. Which is exactly "sometimes it has
    // values, sometimes it doesn't".
    retry: 2,
    retryDelay: (attempt) => Math.min(1500 * 2 ** attempt, 8000),
    refetchOnWindowFocus: true,
  });

  const collapsed = useAppStore((st) => st.tickerCollapsed);
  const toggleCollapsed = useAppStore((st) => st.toggleTickerCollapsed);
  const [winIdx, setWinIdx] = useState(0);
  const [paused, setPaused] = useState(false);
  const win = TREND_WINDOWS[winIdx];

  /**
   * OPEN ON A WINDOW THAT ACTUALLY HAS DATA.
   *
   * The windows are NOT equally answerable, and which ones are changes as the
   * archive ages. Each compares a recent span against the span of equal length
   * before it, so a window needs history reaching back TWICE its length — and
   * the archive's real start is 2026-07-16, about a month deep.
   *
   * Measured against the live archive on 2026-08-14 (recent / prior live rows):
   *
   *     24h    57,163 / 61,764   answerable, and the most volatile — one day
   *                              against one day, before the day is complete
   *     7d     99,652 / 95,314   answerable, and steady
   *     30d   155,053 /      0   NOT answerable: 30-60 days back is empty
   *
   * So the long window is the one that cannot answer, which is the reverse of
   * the intuition that a longer span is the safer default. And the DEFAULT was
   * the volatile one: a 24h reading thins out early in the UTC day, before the
   * nightly cron has filled it in, at which point the bar announced "not
   * enough archive history" with 95,000 rows of perfectly good 7-day history
   * sitting one window along. That is the intermittency.
   *
   * Opening on the shortest window that returned rows is not a fudge: every
   * window is the same measurement over a different span, and the span is
   * named beside the figures either way (see .tlblwin / .tlblwinshort). The
   * alternative is a bar that says nothing while real data sits one window
   * along.
   *
   * A manual pick wins from then on — this only chooses the opening window.
   */
  const userPickedWindow = useRef(false);
  useEffect(() => {
    if (!live || userPickedWindow.current) return;
    const i = TREND_WINDOWS.findIndex((w) => (live[w.key]?.length ?? 0) > 0);
    if (i >= 0) setWinIdx(i);
  }, [live]);

  const rows = live?.[win.key];
  // Three distinct states, and conflating any two of them is what let invented
  // figures onto the ticker:
  //   loading      — the query has not returned. A skeleton, not numbers.
  //   no history   — the archive is too young for THIS window's comparison, so
  //                  the server returned nothing on purpose. Say that.
  //   live         — real movers.
  // FOUR states, not three. `loading` used to be `!live`, which folded a
  // FAILED read in with a pending one — so a failure showed the skeleton
  // forever, looking like a request still in flight rather than one that had
  // already given up. Reading the query's own flags keeps them apart.
  const loading = pending;
  // Memoised because the empty branch is a fresh array literal: without this,
  // `items` changes identity every render and the flash effect below — which
  // depends on it — would re-run continuously.
  /**
   * THE LAST REAL ROWS FOR THIS WINDOW, KEPT FOR THE SESSION.
   *
   * The bar's figures come from a once-a-day cron, so WITHIN one page view a
   * change from "here are the movers" to "there is nothing" is never news
   * about the labour market — it is the read failing, or a refetch landing
   * empty. Blanking a bar that was showing real data is the one outcome that
   * is always wrong, and it is what the flicker looked like: figures, then
   * nothing, then figures again.
   *
   * Keyed by window, so switching windows still shows that window's own data
   * rather than the previous one's. `EMPTY_ITEMS` is still returned when a
   * window has never had rows — a genuine empty stays empty.
   */
  const lastGood = useRef<Partial<Record<TrendWindow, TickerItem[]>>>({});
  if (rows && rows.length) lastGood.current[win.key] = rows;
  const items: TickerItem[] = useMemo(
    () => (rows && rows.length ? rows : (lastGood.current[win.key] ?? EMPTY_ITEMS)),
    [rows, win.key],
  );
  const noHistory = !loading && items.length === 0;
  // Cycling is only offered when there is real data to cycle THROUGH; on the
  // seed every window would show the same fabricated figures.
  const anyLive = !!live && TREND_WINDOWS.some((w) => (live[w.key]?.length ?? 0) > 0);

  // Flash the delta chip on rows whose value actually moved. `items` is a stable
  // reference (query data or the module-level seed), so this runs on a real data
  // change or a window switch, not on every render.
  const lastValues = useRef<Record<string, number>>({});
  const [flashed, setFlashed] = useState<ReadonlySet<string>>(new Set());
  useEffect(() => {
    const changed = new Set<string>();
    for (const t of items) {
      const before = lastValues.current[t.name];
      if (before !== undefined && Math.abs(before - t.v) >= 0.05) changed.add(t.name);
      lastValues.current[t.name] = t.v;
    }
    if (!changed.size) return;
    setFlashed(changed);
    const id = setTimeout(() => setFlashed(new Set()), 800);
    return () => clearTimeout(id);
  }, [items]);

  // The 30-day window draws the full month; the shorter windows draw the tail of
  // the same daily series, as the design's fixed 14-point line does.
  const sparkDays = win.days >= 30 ? 30 : 14;

  const renderItem = (t: TickerItem, key: string) => {
    const dir = dirOf(t.v);
    const path = sparkPath(t.spark ? t.spark.slice(-sparkDays) : undefined);
    return (
      <div className="titem" key={key}>
        <span className="tname">{t.name}</span>
        {path && (
          <svg
            className={`tspark ${dir}`}
            viewBox={`0 0 ${SPARK_W} ${SPARK_H}`}
            width={SPARK_W}
            height={SPARK_H}
            fill="none"
            stroke="currentColor"
            aria-hidden
          >
            <path d={path} />
          </svg>
        )}
        {t.pay !== undefined && (
          <span
            className="tpay"
            title={`Median advertised salary across live vacancies demanding this skill, converted to AUD at rates as at ${FX_AS_AT}`}
          >
            {fmtPay(t.pay)}
          </span>
        )}
        <span className={`tdelta ${dir}${flashed.has(t.name) ? " flash" : ""}`}>
          <svg
            viewBox="0 0 12 12"
            width={11}
            height={11}
            fill="none"
            stroke="currentColor"
            aria-hidden
          >
            <line x1="6" y1="10" x2="6" y2="2" />
            <polyline points="2.5 5.5 6 2 9.5 5.5" />
          </svg>
          <span className="tpct">{(t.v > 0 ? "+" : "") + t.v.toFixed(1)}%</span>
          {/* Names what the percentage measures. Without it the figure sits
              beside a dollar amount and reads as a change in PAY, which is the
              one thing it is not — it is the change in how many vacancies
              demand the skill. */}
          <span className="tdunit">Demand</span>
        </span>
      </div>
    );
  };

  // BOTH STATES ARE ALWAYS MOUNTED, and the collapsed one is the pill.
  //
  // The first version returned one or the other, which is why the toggle looked
  // janky: React tore down a full-width strip and built a centred pill in the
  // same frame, so there was never a moment where both existed for the browser
  // to interpolate between. Nothing was animating — the swap was instant and
  // the eye read it as a glitch.
  //
  // Keeping both and cross-fading costs one hidden subtree. The marquee keeps
  // running underneath while collapsed, which is deliberate: it means expanding
  // is a fade rather than a fade plus a re-layout and a restarted animation.
  // The skill-trends query is shared and cached for six hours, so a mounted
  // hidden strip does not fetch anything extra.
  //
  // `inert` takes the hidden one out of the tab order and the accessibility
  // tree — without it the strip's window/pause buttons stay focusable behind a
  // pill that is visually the only thing on screen.
  //
  // Motion is suppressed globally by `.reduce-motion *`, so the preference
  // needs nothing here.
  // COLLAPSED: a centred pill instead of the full-width strip.
  //
  // Deliberately not "hide the ticker". The strip is the app's one always-on
  // signal that the archive is live, and a reader who tucks it away to see more
  // map still needs to know it is there — so what is left says what it is, and
  // reopens on one click. `data-tour="ticker"` stays on whichever element is
  // rendered, so the guided tour still has something to point at either way.
  const pill = (
    <div
      className={`tickerpill ${hidden ? "zoomhide" : ""}${collapsed ? "" : " tkgone"}`}
      data-tour={collapsed ? "ticker" : undefined}
      inert={!collapsed || undefined}
    >
      <button type="button" onClick={toggleCollapsed} aria-expanded={false}>
        <svg
          viewBox="0 0 24 24"
          width={18}
          height={18}
          fill="none"
          stroke="currentColor"
          strokeWidth={2}
          strokeLinecap="round"
          strokeLinejoin="round"
          aria-hidden
        >
          <polyline points="2 12 7 12 10 5 14 19 17 12 22 12" />
        </svg>
        <span>Live trends</span>
        <svg
          className="tpillchev"
          viewBox="0 0 24 24"
          width={16}
          height={16}
          fill="none"
          stroke="currentColor"
          strokeWidth={2}
          strokeLinecap="round"
          strokeLinejoin="round"
          aria-hidden
        >
          <polyline points="18 15 12 9 6 15" />
        </svg>
      </button>
    </div>
  );

  return (
    <>
      {pill}
      <div
        className={`ticker ${hidden ? "zoomhide" : ""}${collapsed ? " tkgone" : ""}`}
        data-tour={collapsed ? undefined : "ticker"}
        inert={collapsed || undefined}
      >
        {/* Two labels, one shown at a time by breakpoint. At 390px the bar is
            the full width of the map card, and "Skills in demand · Last 30
            days" ate close to half of it — leaving the scrolling skills, which
            are the actual content, a sliver. The design's answer is a compact
            "LIVE" pill, so that is what phones get. */}
        <div className="tickerlbl">
          <i />
          <span className="tlblfull">Skills in demand</span>
          <span className="tlblshort">Live</span>
          <span className="tlblwin">{win.label}</span>
          {/* The same fact as .tlblwin, at a width a phone can carry. It is
              NOT decoration and it is not optional: these deltas are a
              comparison over a span, the span is now chosen automatically
              from what the archive holds, and a percentage whose window is
              unstated is the kind of number this codebase exists not to
              print. .tlblwin is hidden below 680px; this replaces it. */}
          <span className="tlblwinshort">{win.short}</span>
        </div>

        <div className="tickerwrap">
          {loading ? (
            <div className="tickertrack skeleton" aria-hidden>
              {[...SKELETON, ...SKELETON].map((w, i) => (
                <div className="titem" key={i}>
                  <span className="tskel" style={{ width: w }} />
                </div>
              ))}
            </div>
          ) : failed ? (
            // Named as a fault rather than dressed up as "no data": the
            // archive not answering and the archive having nothing to say are
            // different facts, and only one of them is about the labour market.
            <div className="tickerempty">Live demand is unavailable right now.</div>
          ) : noHistory ? (
            <div className="tickerempty">
              Not enough archive history yet to measure change over{" "}
              {win.label.replace("· Last ", "the last ").toLowerCase()}.
            </div>
          ) : (
            <div className={`tickertrack${paused ? " paused" : ""}`}>
              {items.map((t, i) => renderItem(t, "a" + i))}
              {items.map((t, i) => renderItem(t, "b" + i))}
            </div>
          )}
        </div>

        <div className="tickerctl">
          <button
            type="button"
            className="tickerwin"
            onClick={() => {
              userPickedWindow.current = true;
              setWinIdx((i) => (i + 1) % TREND_WINDOWS.length);
            }}
            disabled={!anyLive}
            aria-label={`Trend window: ${win.short}`}
          >
            {/* The pause button beside it has always had the design's dark tip;
              this one was on the browser's native `title`, which looks like a
              different product and waits a second before appearing. */}
            <span className="tickertip">
              {anyLive
                ? `Showing ${win.label.replace("· ", "").toLowerCase()} — click to change`
                : "Comparison windows unlock once the job archive has history"}
            </span>
            {win.short}
          </button>
          <button
            type="button"
            className="tickerpause"
            onClick={() => setPaused((p) => !p)}
            aria-label={paused ? "Resume ticker" : "Pause ticker"}
            aria-pressed={paused}
          >
            <span className="tickertip">{paused ? "Resume ticker" : "Pause ticker"}</span>
            <svg
              className={paused ? "paused" : ""}
              viewBox="0 0 24 24"
              width={18}
              height={18}
              fill="none"
              stroke="currentColor"
              aria-hidden
            >
              <line x1="9.5" y1="5" x2="9.5" y2="19" />
              <line x1="14.5" y1="5" x2="14.5" y2="19" />
            </svg>
          </button>
          {/* Far right of the cluster, after the window and pause controls —
            the order the reader meets them in: change what it shows, stop it
            moving, put it away. */}
          <button
            type="button"
            className="tickercollapse"
            onClick={toggleCollapsed}
            aria-label="Collapse the ticker"
            aria-expanded
          >
            <span className="tickertip">Collapse</span>
            <svg
              viewBox="0 0 24 24"
              width={18}
              height={18}
              fill="none"
              stroke="currentColor"
              strokeWidth={2}
              strokeLinecap="round"
              strokeLinejoin="round"
              aria-hidden
            >
              <polyline points="6 9 12 15 18 9" />
            </svg>
          </button>
        </div>
      </div>
    </>
  );
}
