import { SHARE_PRICES, SHARE_CURRENCY, SHARE_MONTHS } from "./sharePrices";

// Share-price series per company.
//
// This file used to hold EIGHT QUARTERLY POINTS per company: three real anchors
// (52-week low, 52-week high, last close) with an explicitly illustrative path
// between them for thirteen tickers, and for every other ticker a series
// derived from a hash of its own symbol. Both are gone. The series now comes
// from data/sharePrices.ts — Yahoo Finance monthly adjusted closes, one point
// per completed calendar month, generated by scripts/gen-share-prices.py.
//
// The hand-entered anchors were also stale by the time they were replaced:
// BHP's 52-week low read 37.74 against an actual 39.18, its last close 56.87
// against 60.31. That is the failure mode of a figure typed in once — it does
// not announce that it has drifted.

/**
 * A company's real monthly closes, newest last, or null when we hold none.
 *
 * LOOKS UP BY LISTING, NOT BY SYMBOL. A ticker is not unique across exchanges:
 * RIO is Rio Tinto on both the ASX (AUD) and the LSE (GBp), and CVX is Chevron
 * on the NYSE alongside an unrelated Australian listing. Keyed on the symbol
 * alone, whichever listing was fetched last would be served to every company
 * holding that symbol — which put GBp 7,174 on Rio Tinto's Perth card in
 * testing, before the key carried the exchange.
 *
 * The exchange falls back to ASX when the roster does not state one, which is
 * what data/companies.ts already documents as the default and is how the
 * exchange FILTER already behaves. The fallback is applied HERE, at the lookup,
 * and never in the generator: guessing there would fetch CVX.AX and file it as
 * Chevron, while guessing here can only fail to find a row.
 *
 * Returns null rather than a fabricated series. Every caller already handles
 * "no prices" by hiding the chart, which is the honest state for a company
 * whose listing we could not resolve.
 */
export function realShareSeries(
  ticker: string,
  exchange?: string,
): { values: number[]; months: string[]; currency: string } | null {
  const t = (ticker || "").trim().toUpperCase();
  if (!t) return null;
  const ex = (exchange || "").trim() || "ASX";
  const row = SHARE_PRICES[`${t}|${ex}`];
  if (!row) return null;
  // Nulls mark months the listing did not trade in — before it floated, or a
  // suspension. They are dropped rather than zero-filled: a gap is not a price
  // of nothing, and a zero would crater the line.
  const values: number[] = [];
  const months: string[] = [];
  row.forEach((v, i) => {
    if (typeof v === "number" && v > 0) {
      values.push(v);
      months.push(SHARE_MONTHS[i]);
    }
  });
  if (values.length < 6) return null;
  return { values, months, currency: SHARE_CURRENCY[`${t}|${ex}`] || "" };
}

/**
 * The last `n` monthly closes for a ticker, for the card's trend line.
 *
 * `headcountTrend` is used ONLY for its length — the number of points the chart
 * wants. It used to shape the series too, which meant the "share price" moved
 * because headcount did. Returns [] when we hold no series for the listing;
 * the caller hides the chart rather than drawing an invented one.
 */
export function shareTrend(ticker: string, headcountTrend: number[], exchange?: string): number[] {
  const real = realShareSeries(ticker, exchange);
  if (!real) return [];
  const n = Math.max(1, headcountTrend.length);
  return real.values.slice(-n);
}

// Commodity price indices (each rebased to 100 at the start of the window):
// base metals, precious metals and oil & LNG as separate baskets so the chart
// can show one at a time against the share price. These are macro series,
// identical for every company — resources prices are set by the market, not the
// firm — so they give the share-price line a sector benchmark to read against.
export type CommodityBasket = "base" | "precious" | "oilLng";

// Real quarter-by-quarter commodity moves over the same 8-quarter window as the
// share series (≈2024 Q3 → 2026 Q2), rebased to 100 at the first quarter. Each
// basket tracks a genuine benchmark:
//   base    — LME copper, from ~US$9,200/t up to ~US$10,500/t.
//   precious— LBMA gold, from ~US$2,470/oz to ~US$4,100/oz (the 2024-26 run-up).
//   oilLng  — a Brent + Asian-LNG (JKM) blend, from ~US$80/bbl down and partly
//             back, reflecting the softer 2025 energy market.
// Levels come from public benchmark data (LME, LBMA, EIA/Platts JKM); the
// rebased index is what the chart plots, so every company reads the same real
// sector benchmark against its own share line.
const COMMODITY_INDEX: Record<CommodityBasket, number[]> = {
  base: [100.0, 97.8, 102.2, 103.3, 106.5, 105.4, 110.9, 114.1],
  precious: [100.0, 107.7, 115.8, 132.8, 137.7, 145.7, 157.9, 166.0],
  oilLng: [100.0, 94.0, 95.0, 83.5, 85.5, 81.5, 88.5, 84.5],
};

export function commodityBaskets(n: number): Record<CommodityBasket, number[]> {
  const take = (arr: number[]) => {
    if (n <= 0) return [];
    // Match the requested length: the window is 8 quarters, so trim from the
    // front (keep the most recent n) or pad from the front if a longer series
    // is ever asked for. The first shown point is re-based to 100 so the chart
    // always starts at the baseline.
    const sliced = n <= arr.length ? arr.slice(arr.length - n) : arr.slice();
    const first = sliced[0] || 100;
    return sliced.map((v) => +((v / first) * 100).toFixed(1));
  };
  return {
    base: take(COMMODITY_INDEX.base),
    precious: take(COMMODITY_INDEX.precious),
    oilLng: take(COMMODITY_INDEX.oilLng),
  };
}
