import type { Company, RoleBreakdown } from "./companies";
import { deriveDomain } from "./rosters";

// New Zealand public-sector agencies — the NZ counterpart of canberraGov.ts /
// adelaideGov.ts, harvested from the government jobs board (jobs.govt.nz) and
// archived daily in D1 under source 'nz-gov' (scripts/nzgov-to-d1.py).
//
// SCOPE: only agencies advertising in Auckland or Wellington are listed. The
// board covers the whole country, but those are the two NZ cities the app plots,
// and an agency with no pin has nowhere to live. Agencies elsewhere still get
// scraped and archived — they simply are not roster cards yet.
//
// ids are `nz-<slug>`, generated by exactly the same rule as agency_id() in the
// scraper (lowercase, non-alphanumerics collapsed to '-', trimmed, prefixed,
// truncated to 60). They MUST stay byte-identical to the ids written into D1 or
// a card resolves no vacancies. That rule is why a couple read oddly:
// "NZ Police" becomes `nz-nz-police`, and macrons are dropped rather than
// transliterated, so Waitematā becomes `…-waitemat`. Both are kept as-is —
// matching the archive matters more than a tidy slug.
//
// The hub is where each agency actually advertises most, taken from the harvest
// rather than assumed: NZ's public service is Wellington-centred, but the health
// districts and a few others are Auckland employers.
//
// To refresh this list when the board's employer set changes, run
//   python scripts/nzgov-to-d1.py --agencies
// which prints {id, name, city, roles} for everything it saw, and reconcile the
// table below against it. It is a deliberate manual step: a new agency needs a
// sector and a hub decided, not just an id.
//
// The four Te Whatu Ora districts and the Northern Regional Alliance are health
// employers, not central-government ones, so they carry the Healthcare sector
// and group — the Healthcare filter should find a hospital district, and the
// Government filter should not be the only way to reach it.
type AgencyEntry = [name: string, hub: "auckland" | "wellington", seenRoles: number];

// [agency, hub, roles observed in the first full harvest]
const AGENCIES: AgencyEntry[] = [
  ["Health New Zealand - Te Whatu Ora Te Toka Tumai Auckland", "auckland", 101],
  ["Health New Zealand - Te Whatu Ora Counties Manukau", "auckland", 67],
  ["Health New Zealand - Te Whatu Ora Waitematā", "auckland", 64],
  ["Health New Zealand - Te Whatu Ora Capital, Coast & Hutt Valley", "wellington", 57],
  ["Electoral Commission", "auckland", 26],
  ["Accident Compensation Corporation", "wellington", 21],
  ["NZ Police", "wellington", 21],
  ["Ministry of Business, Innovation and Employment", "wellington", 17],
  ["Department of Internal Affairs", "wellington", 14],
  ["New Zealand Transport Agency", "wellington", 14],
  ["Northern Regional Alliance (NRA)", "auckland", 14],
  ["Department of Conservation", "auckland", 12],
  ["Ministry of Education", "wellington", 10],
  ["Oranga Tamariki—Ministry for Children", "wellington", 8],
  ["Reserve Bank of New Zealand", "wellington", 7],
  ["Transpower New Zealand Limited", "wellington", 7],
  ["Statistics NZ", "wellington", 5],
  ["The Treasury", "wellington", 5],
  ["Civil Aviation Authority of NZ", "wellington", 4],
  ["Environmental Protection Authority", "wellington", 3],
  ["Government Communications Security Bureau", "wellington", 3],
  ["Maritime New Zealand", "wellington", 3],
  ["New Zealand Customs Service", "wellington", 3],
  ["NZ Security Intelligence Service (NZSIS)", "wellington", 3],
  ["Te Puni Kōkiri - Ministry of Māori Development", "wellington", 3],
  ["Financial Markets Authority", "auckland", 2],
  ["Kāinga Ora – Homes and Communities", "auckland", 2],
  ["New Zealand Lotteries Commission", "auckland", 2],
  ["Public Service Commission Te Kawa Mataaho", "wellington", 2],
  ["Te Papa", "wellington", 2],
  ["Department of the Prime Minister & Cabinet", "wellington", 1],
  ["Ministry of Foreign Affairs & Trade", "wellington", 1],
  ["Natural Hazards Commission Toka Tū Ake", "wellington", 1],
  ["Victoria University of Wellington", "wellington", 1],
];

// Agencies that are health employers rather than central government.
const HEALTH_RE = /Te Whatu Ora|Northern Regional Alliance/;

const STOP = new Set(["of", "and", "the", "for", "&", "a"]);

function h01(s: string): number {
  let h = 2166136261;
  for (let i = 0; i < s.length; i++) {
    h ^= s.charCodeAt(i);
    h = Math.imul(h, 16777619);
  }
  return ((h >>> 0) % 100000) / 100000;
}

// Must match agency_id() in scripts/nzgov-to-d1.py exactly — see the note above.
export function nzAgencyId(name: string): string {
  const slug = name
    .toLowerCase()
    .replace(/[^a-z0-9]+/g, "-")
    .replace(/^-|-$/g, "");
  return ("nz-" + slug).slice(0, 60);
}

function govAcronym(name: string): string {
  const words = name.split(/[\s,]+/).filter((w) => w && !STOP.has(w.toLowerCase()));
  if (words.length >= 2) {
    return words
      .map((w) => w[0].toUpperCase())
      .join("")
      .slice(0, 6);
  }
  return (words[0] || name).slice(0, 5).toUpperCase();
}

const GOV_SKILLS = [
  "Policy & Governance",
  "Public Administration",
  "Project Delivery",
  "Data & Analytics",
  "Community Services",
];
const HEALTH_SKILLS = [
  "Nursing",
  "Allied Health",
  "Medical Practice",
  "Health Administration",
  "Community Services",
];
const GOV_ROLES = ["Corporate & Policy", "Frontline Services", "Operations"];
const HEALTH_ROLES = ["Clinical", "Nursing & Midwifery", "Corporate & Support"];

function buildAgency([name, , seenRoles]: AgencyEntry): Company {
  const health = HEALTH_RE.test(name);
  const h = h01(name);
  const h2 = h01(name + "::b");
  // NZD bands, lower than the APS equivalents.
  const salaryNum = Math.round((92 + (h - 0.5) * 40) * 1000); // ~72k .. 112k
  const salaryK = Math.round(salaryNum / 1000);
  const turnover = +(7 + h2 * 8).toFixed(1);
  // openRoles seeds from what the first harvest actually saw, not a hash — a
  // card that is opened replaces it with the live count from D1 (see
  // lib/openRolesFn.ts), so this is only what shows before that resolves.
  const split = [0.45, 0.33, 0.22];
  const roleTitles = health ? HEALTH_ROLES : GOV_ROLES;
  const roles: RoleBreakdown[] = roleTitles.map((title, i) => ({
    title,
    count: Math.max(1, Math.round(seenRoles * split[i])),
  }));
  const delta = Math.round((h - 0.5) * 16);
  const acr = govAcronym(name);
  return {
    id: nzAgencyId(name),
    ticker: acr,
    name,
    pill: acr,
    domain: deriveDomain(name),
    sector: health ? "Healthcare" : "Government",
    group: health ? "Healthcare and Life Sciences" : "Infrastructure and Government",
    private: true,
    headcount: 0,
    growth: 0,
    openRoles: seenRoles,
    salary: `$${salaryNum.toLocaleString("en-US")}`,
    salaryShort: `$${salaryK}K`,
    salaryNum,
    turnover,
    salaryDelta: `${delta >= 0 ? "+" : "−"}${Math.abs(delta)}%`,
    metroDelta: `${delta >= 0 ? "+" : "−"}${Math.abs(delta)}% vs metro`,
    trend: [],
    revPerEmp: 0,
    ebitdaPerEmp: 0,
    timeToFill: `${Math.round(30 + h * 26)} days`,
    competition: h > 0.66 ? "High" : h > 0.33 ? "Medium" : "Low",
    skills: health ? HEALTH_SKILLS : GOV_SKILLS,
    roles,
  };
}

export const NZ_GOV_COMPANIES: Company[] = AGENCIES.map(buildAgency);
export const NZ_GOV_IDS: string[] = NZ_GOV_COMPANIES.map((c) => c.id);
export const NZ_GOV_NAMES: string[] = AGENCIES.map(([name]) => name);

// id → hub (Auckland or Wellington) so the map pins each agency in the city it
// actually advertises in. Used by mapboxGeo.ts.
export const NZ_GOV_HUB: Record<string, string> = Object.fromEntries(
  AGENCIES.map(([name, hub]) => [nzAgencyId(name), hub]),
);
