// SEEK advertiser ids a company hires under that are NOT its own name.
//
// WHY THIS FILE EXISTS
// seekAdvertisers.ts is generated by scripts/gen-seek-advertisers.py, which
// accepts an advertiser only when its own description matches the roster name
// exactly (after stripping corporate form). That rule is deliberately strict —
// it is what stops a recruiter or a same-word company being filed as the
// employer — and it is therefore blind to the ordinary case of a group whose
// people are hired by its operating businesses under THEIR brands. Measured
// against the live SEEK API on 2026-08-08, that blindness was costing 237 live
// ads across five Perth companies, four of which looked to us like employers
// who simply were not hiring:
//
//   Perenti          mapped id 45401581 returns 0. All ~105 ads sit under the
//                    seven brands below.
//   Austal           no map entry at all; 76 ads under "Austal Ships".
//   Alkane Resources no map entry; 29 ads under its two mines' names.
//   Seven West Media no map entry; 16 ads under "Seven" and the newspaper arm.
//   Catalyst Metals  no map entry; 9 ads under the Plutonic operating entity.
//
// It is a SEPARATE file, and not extra rows in seekAdvertisers.ts, for the
// reason EXTRA_QUERIES gives in workers/jobs-cron/companyQueries.ts: that file
// is generated, so a hand-added entry is lost on the next run. These are
// hand-researched corporate facts and live where no generator writes.
//
// WHAT AN ENTRY ASSERTS
// That the parent company employs the people advertised under this advertiser
// id. An ad found here is filed against the PARENT, so a wrong entry does not
// add noise — it credits one employer with another's hiring. Every id below was
// resolved against the live search API and then confirmed by reading the ads it
// serves (site names, office locations, the employer's own wording), and the
// group structure was confirmed against the company's own material. `live` is
// what the id was serving when it was added: a sanity figure, not a threshold.
//
// Adding one: search SEEK for the brand, take the advertiser whose description
// starts with it, pull that id directly to confirm it is the employer and not a
// recruiter advertising on their behalf, then record the count here.
//
// This only decides which BOARDS get pulled. The other half — attributing an ad
// that arrives from a keyword feed under one of these names — is
// ADVERTISER_ALIAS in scripts/advertiser_match.py, and making those feeds look
// for the name at all is EXTRA_QUERIES in companyQueries.ts.
import { SEEK_ADVERTISERS, type SeekAdvertiser } from "./seekAdvertisers";

export const SEEK_TRADING_NAMES: Record<string, SeekAdvertiser[]> = {
  // Austal (ASX:ASB) builds ships as Austal Ships — the entity its Henderson WA
  // yard and its Philippine yard at Balamban both advertise under. The bare
  // "Austal" has no advertiser record at all, which is why the generator found
  // nothing. scripts/advertiser_match.py already carries the matching alias.
  asb: [{ advertiserId: "400227768", name: "Austal Ships" }], // live 76

  // Perenti (ASX:PRN) is a mining-services group that advertises entirely
  // through its brands; the "Perenti Group" advertiser id the generator resolved
  // is real but has served 0 ads every time it has been checked. Confirmed
  // against Perenti's own "our businesses" listing:
  //   Contract mining   — Barminco, AUMS (African Underground Mining Services)
  //   Drilling services — DDH1, Ausdrill, Strike Drilling, Swick
  //   Mining services   — BTP
  // Ranger Drilling, Supply Direct, Logistics Direct and idoba are also Perenti
  // brands but had no SEEK advertiser record when this was built — they are
  // omitted rather than guessed, and belong here the day they appear.
  "perth-prn": [
    { advertiserId: "7321245", name: "Barminco Pty Ltd" }, // live 56
    { advertiserId: "22200893", name: "DDH1 Drilling Pty Ltd" }, // live 18
    { advertiserId: "29360304", name: "BTP Group" }, // live 12
    { advertiserId: "2582", name: "Ausdrill Limited" }, // live 10
    { advertiserId: "61449958", name: "AUMS" }, // live 5
    { advertiserId: "21592492", name: "Swick Mining Services" }, // live 4
    { advertiserId: "31269159", name: "Strike Drilling" }, // live 2
  ],

  // Alkane Resources (ASX:ALK) advertises under its two producing mines, never
  // under the corporate name. Costerfield (gold-antimony, Victoria) came with
  // the Mandalay Resources merger completed 2025-08-05; Tomingley (gold, NSW)
  // is the original Alkane operation. Björkdal, the Swedish mine also acquired
  // in that merger, is out of scope for an AU board.
  alk: [
    { advertiserId: "27277319", name: "Costerfield Operations" }, // live 21
    { advertiserId: "46081541", name: "Tomingley Gold Operations" }, // live 8
  ],

  // Seven West Media (ASX:SWM) hires under its mastheads and its network brand.
  // "Seven" is the television arm — confirmed from the ads themselves (Seven
  // news teams in regional bureaux, the Eveleigh Sydney office). Note there is
  // an unrelated "Seven Miles Coffee Roasters" on SEEK; it is a different
  // advertiser id and is not listed here.
  swm: [
    { advertiserId: "62297189", name: "Seven" }, // live 8
    { advertiserId: "400297504", name: "West Australian Newspapers Limited" }, // live 8
  ],

  // Catalyst Metals (ASX:CYL) advertises through the operating entity for its
  // Plutonic gold mine in WA rather than the listed parent.
  "perth-cyl": [
    { advertiserId: "36323855", name: "CATALYST (PLUTONIC) PTY LTD" }, // live 9
  ],
};

/**
 * Every SEEK advertiser to pull for a company: the generated exact-name match
 * first (when there is one), then any trading names.
 *
 * Deduped by advertiser id, because a brand that later starts matching the
 * roster name exactly would otherwise be resolved into seekAdvertisers.ts AND
 * still be listed here — pulling the same board twice.
 */
export function seekAdvertisersFor(id: string): SeekAdvertiser[] {
  const out: SeekAdvertiser[] = [];
  const seen = new Set<string>();
  const own = SEEK_ADVERTISERS[id];
  for (const adv of [...(own ? [own] : []), ...(SEEK_TRADING_NAMES[id] ?? [])]) {
    if (seen.has(adv.advertiserId)) continue;
    seen.add(adv.advertiserId);
    out.push(adv);
  }
  return out;
}
