/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as MobileFrameRouteImport } from './routes/mobile-frame'
import { Route as IndexRouteImport } from './routes/index'

const MobileFrameRoute = MobileFrameRouteImport.update({
  id: '/mobile-frame',
  path: '/mobile-frame',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/mobile-frame': typeof MobileFrameRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/mobile-frame': typeof MobileFrameRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/mobile-frame': typeof MobileFrameRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/mobile-frame'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/mobile-frame'
  id: '__root__' | '/' | '/mobile-frame'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  MobileFrameRoute: typeof MobileFrameRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/mobile-frame': {
      id: '/mobile-frame'
      path: '/mobile-frame'
      fullPath: '/mobile-frame'
      preLoaderRoute: typeof MobileFrameRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  MobileFrameRoute: MobileFrameRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
